# Default settings for the PDF Outline Extractor

# --- General Settings ---
input_dir: "input"
output_dir: "output"
log_dir: "logs"

# --- Extraction Logic ---
# Method to use: 'bookmarks' (tries bookmarks first, then falls back), 'font_analysis' (forces font analysis)
extraction_method: "bookmarks"

# --- Font Analysis Settings (used if no bookmarks are found) ---
# Any font size difference greater than this is considered a potential heading level break.
min_font_size_difference: 1.0

# A font is considered "bold" if its weight is >= this value. (Common values are 400 for normal, 700 for bold)
bold_threshold: 600

# Top N most frequent font styles to consider as "body text" and ignore.
ignore_top_n_styles: 1